version: '3.9'
services:
#Le colocamos nombre a nuestro contenedor como pomodoroweb
  pomodoroweb:
#Se crea una imagen a partir de la imagen del archivo Dockerfile de la carpeta Frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
 # Mapear puertos.
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - pomodoro-networks
networks:
  pomodoro-networks:
    driver: bridge 
    



