version: '3.8'
services:
  Pomodoro_Web:
    build: ./frontend
    ports:
      - "8080:80"
    restart: unlesss-stopped
    networks:
      - Pomodoro-networks
networks:
  pomodoro-networks:
    driver: bridge 
    



